### PR TITLE
esn-frontend-inbox#53: Fixed LinshareApiClient wrapper

### LINKED ISSUE #53: Bring back the Linshare upload provider when composing an email
att2
att1

TODOs:

- [x] 1. Bring back `linagora.esn.linshare` in a repository named `esn-frontend-linshare`.
- [x] 2. Bring back `linagora.esn.unifiedinbox.linshare` in a repository named `esn-frontend-linshare-inbox`. The Inbox SPA needs to require this.
- [x] 3. Move all shared dependencies in `linagora.esn.unifiedinbox` to `esn.inbox.libs`.
- [ ] 4. Remove all dynamic directives and injecting the LinShare attachment button into the mail composer in `esn-frontend-inbox`.
- [x] 5. Check if everything works by:
     - [x] 5.1. Setting up LinShare's backend
     - [x] 5.2. Registering OpenPaaS' Public Key into LinShare
- [ ] 6. Add translation to `esn-frontend-linshare` and `esn-frontend-inbox-linshare`.

### PR DESCRIPTION
**Pull request by itswillta**
Partially resolves https://github.com/OpenPaaS-Suite/esn-frontend-inbox/issues/53. Please refer to https://github.com/OpenPaaS-Suite/esn-frontend-inbox/pull/59 for the demo.

### CODE REVIEW

**Review by tuanlc — APPROVED** [review]
What is the issue?

**Comment by itswillta** [comment]
> What is the issue?

In `linshareApiClientProvider`, it uses `new LinshareApiClient.Client()`, so the previous code doesn't work.

**Comment by tuanlc** [comment]
> In linshareApiClientProvider, it uses new LinshareApiClient.Client(), so the previous code doesn't work.

Hmm. Did the feature work before in the old codebase?  :thinking:

**Comment by itswillta** [comment]
> > In linshareApiClientProvider, it uses new LinshareApiClient.Client(), so the previous code doesn't work.
> 
> Hmm. Did the feature work before in the old codebase?

Yes. However, when adding explicit dependencies, I used `const { Client } = require('linshare-api-client');`, which introduced the bug.

**Review by piavgh — APPROVED** [review]

**Pull request merged**
